name = "Minimal Project"
license = "MIT"
licenselink = "https://github.com/sowmyamanojna/hugo-minimal-project/blob/master/LICENSE.md"
description = "Theme for documenting Projects."

homepage = "https://github.com/sowmyamanojna/hugo-minimal-project/"
demosite = "https://sowmyamanojna.github.io/hugo-minimal-project/"

tags = ["documentation", "project", "landing page", "opensource", "single page"]
features = ["github", "images", "inline math", "emoji", "code highlighting", "tables"]

[author]
    name = "N Sowmya Manojna"
    homepage = "https://sowmyamanojna.github.io"

# If porting an existing theme
[original]
    author =  "Christian Decker"
    homepage = "https://github.com/cdeck3r/OneDly-Theme"
    repo = "https://github.com/cdeck3r/OneDly-Theme"
